#ifndef TRIANGLES_I2PSEED_H
#define TRIANGLES_I2PSEED_H

// Hardcoded I2P seed nodes for initial peer discovery.
// These are .b32.i2p addresses (Destination hashes).
// Nodes must run i2pd with a server tunnel forwarding to the Triangles P2P port.
//
// NOTE: .b32.i2p addresses are derived from the destination's public key.
// They are generated when the node first creates its I2P tunnel keys.
// Replace these placeholders with actual seed node addresses once deployed.
//
// Dynamic seeds will also be available at:
//   https://seeds.cryptographic-triangles.org/i2p-seeds.txt
static const char *strMainNetI2PSeed[][1] = {
    // SAMI-PC - authoritative wallet node (main PC)
    {"fecv4pomdm47epuadgrpkvxzjqfqwsjfc7t7xadwaac5bislyrhq.b32.i2p"},
    // DNS2 - primary bootstrap server (194.233.88.206)
    // Generated by embedded i2pd on first run, keys persist in i2p_data/
    {"hnupgkbtcn4hlo6sunhbp6uuz4k6bkgsa5jtcruyyt7y6q7qsoda.b32.i2p"},
    // DNS3 - canonical chain reference (74.208.167.19)
    {"hvvr2yys3nll4l6fdywecvn3baw6h5i7bsa2ldbz2e5xwangnn7q.b32.i2p"},
    // Hetzner Helsinki - ARM64 staking node (46.62.249.20)
    {"2hyeunnkax5du4snip4gdsdicxtmlnagtlkatv57rjpx2kvfssma.b32.i2p"},
    {nullptr}
};

static const char *strTestNetI2PSeed[][1] = {
    {nullptr}
};

#endif
